agents:
  PDM4AR_1:
    state:
      x: -20
      y: -40
      psi: 1
    goal: 16
    color: 'red'
  PDM4AR_2:
    state:
      x: -20
      y: -40
      psi: 1
    goal: 16
    color: 'green'
  PDM4AR_3:
    state:
      x: -20
      y: -40
      psi: 1
    goal: 16
    color: 'blue'
  PDM4AR_4:
    state:
      x: -20
      y: -40
      psi: 1
    goal: 16
    color: 'saddlebrown'

static_obstacles:
  - [ [ 0, 0 ], [ 0, 4 ], [ 4, 4 ], [ 4, 0 ], [ 0, 0 ] ]
  - [ [ 6, 0 ], [ 6, 4 ], [ 10, 4 ], [ 10, 0 ], [ 6, 0 ] ]
  - [ [ 12, 0 ], [ 12, 4 ], [ 16, 4 ], [ 16, 0 ], [ 12, 0 ] ]
  - [ [ 0, 6 ], [ 0, 10 ], [ 4, 10 ], [ 4, 6 ], [ 0, 6 ] ]
  - [ [ 6, 6 ], [ 6, 10 ], [ 10, 10 ], [ 10, 6 ], [ 6, 6 ] ]
  - [ [ 12, 6 ], [ 12, 10 ], [ 16, 10 ], [ 16, 6 ], [ 12, 6 ] ]

boundary: [ [ -11, -11 ], [ -11, 11 ], [ 11, 11 ], [ 11, -11 ], [ -11, -11 ] ]

seed: 98